# @package _global_

model:
  arch: anymc3d_backbone
  run_name: anymc3d_backbone_25D_LoRALR_1e-4_Headlr_1e-3_vitb_pdcad
  num_classes: 2
  modalities: [t1c]
  backbone_name: dinov2_vitb14
  lora_rank: 8
  lora_alpha: 16
  input_size: 308
  dropout: 0.1
  slice_axis: 3
  vision_blocks: 0
  mlp_ratio: 4.0
  block_dropout: 0.0
  use_patch_concat: False
  use_25d: True
  use_patch_attn_pool: False

optimizer:
  lora_lr: 1e-4
  lora_weight_decay: 1e-5
  vision_lr: 1e-4
  vision_weight_decay: 1e-5
  head_lr: 5e-4
  head_weight_decay: 1e-3
  warmup_epochs: 0
  lr_scheduler: cosine